version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: vrweb_nginx
    ports:
      - "8080:443"
    volumes:
      - ./WEB:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro